name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AutoFTbot
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          config_display: large
          config_order: base, isocalendar, languages, stars, topics

          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_notable: yes
          plugin_notable_filter: stars>5
          plugin_traffic: yes
