
name: Notify Telegram on Star

on:
  watch:
    types:
      - started  # Mengirim notifikasi saat repository Anda di-star

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="🎉 Repository Anda di-star oleh: ${{ github.actor }} 🚀"
