name: Install & Remove qris-payment

on:
  schedule:
    - cron: '0 2 * * *'  # Jalan setiap hari jam 02:00 UTC
  workflow_dispatch:      # Bisa dijalankan manual juga

jobs:
  install-and-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Init package.json (jika belum ada)
        run: |
          if [ ! -f package.json ]; then
            echo "[INFO] Membuat package.json..."
            npm init -y
          fi

      - name: Install qris-payment
        run: |
          echo "[INFO] Menginstal qris-payment dari NPM..."
          npm install qris-payment

      - name: Verifikasi bahwa qris-payment sudah terinstal
        run: |
          if [ -d "node_modules/qris-payment" ]; then
            echo "[INFO] qris-payment berhasil diinstal."
          else
            echo "[ERROR] qris-payment tidak ditemukan setelah install."
            exit 1
          fi

      - name: Uninstall qris-payment
        run: |
          echo "[INFO] Menghapus qris-payment..."
          npm uninstall qris-payment

      - name: Hapus semua dependensi dan lock file
        run: |
          echo "[INFO] Membersihkan node_modules dan package-lock.json..."
          rm -rf node_modules
          rm -f package-lock.json
