   name: Generate Snake Animation

   on:
     schedule:
       - cron: "0 0 * * *"
     workflow_dispatch:

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Generate Snake Animation
           uses: Platane/snk@v2
           with:
             github_user_name: ${{ github.repository_owner }}
