name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pukul 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Jalankan Snake Animation Generator
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: AutoFTbot
