     name: Generate Snake Animation

     on:
       schedule:
         - cron: "0 0 * * *"  # Menjalankan setiap hari pada tengah malam
       workflow_dispatch:

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout
             uses: actions/checkout@v2

           - name: Generate Snake Animation
             uses: Platane/snk@v2
             with:
               github_user_name: AutoFTbot
               outputs: dist/snake.svg

           - name: Push Snake Animation
             uses: peaceiris/actions-gh-pages@v3
             with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./dist
