name: Debug via SSH

on:
  workflow_dispatch:  # Bisa dijalankan manual dari tab Actions di GitHub

jobs:
  debug:
    name: Debug with tmate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session (SSH)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false  # Hanya pemilik repo yang bisa SSH
