name: Update Donation Badge

on:
  push:
    paths:
      - 'donations.json'
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AutoFTbot (Repo ini)
        uses: actions/checkout@v2

      - name: Checkout OrderKuota-go
        uses: actions/checkout@v2
        with:
          repository: AutoFTbot/OrderKuota-go
          path: OrderKuota-go
          ref: v1.0.1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Tambahkan replace directive ke go.mod
        run: |
          if ! grep -q 'replace github.com/AutoFTbot/OrderKuota-go' OrderKuota-go/go.mod; then
            echo 'replace github.com/AutoFTbot/OrderKuota-go => ./OrderKuota-go' >> go.mod
          fi

      - name: Konfigurasi Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Hitung Total Donasi
        id: total
        run: |
          echo "[INFO] Cek keberadaan donations.json"
          if [ ! -f donations.json ]; then
            echo "[ERROR] donations.json tidak ditemukan"
            echo "total=0" >> $GITHUB_OUTPUT
            echo "count=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          cd OrderKuota-go
          TOTAL=$(go run ../donation/calculate-total.go)
          cd ..

          if [ -z "$TOTAL" ]; then
            echo "[WARN] Total kosong, set ke 0"
            TOTAL=0
          fi

          PAID_COUNT=$(jq '[.[] | select(.status == "PAID")] | length' donations.json)

          echo "[INFO] Total: Rp $TOTAL ($PAID_COUNT donasi)"
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "count=$PAID_COUNT" >> $GITHUB_OUTPUT

      - name: Debug ID Gist & File
        run: |
          echo "[DEBUG] Gist ID: 86a13cfb221fc094c35b4320e102d759"
          echo "[DEBUG] File: total-donations.json"

      - name: Update Badge di README
        uses: schneegans/dynamic-badges-action@v1.5.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 86a13cfb221fc094c35b4320e102d759
          filename: total-donations.json
          label: "Total Donasi"
          message: ${{ format('Rp {0} ({1} donasi)', steps.total.outputs.total, steps.total.outputs.count) }}
          color: green
          forceUpdate: true
          debug: true

      - name: Cek README
        run: |
          echo "[INFO] Cek apakah README.md ada"
          cat README.md || echo "README.md tidak ditemukan."

      - name: Commit dan Push jika README berubah
        run: |
          git add README.md || true
          if git diff --quiet && git diff --staged --quiet; then
            echo "[INFO] Tidak ada perubahan pada README.md"
          else
            echo "[INFO] Ada perubahan, melakukan commit dan push"
            git commit -m "Update badge donasi: Rp ${{ steps.total.outputs.total }} (${{ steps.total.outputs.count }} donasi)"
            git pull --rebase origin main
            git push
          fi
