name: Update Donation Badge

on:
  push:
    paths:
      - 'donations.json'
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
          
      - name: Calculate total donations
        id: total
        run: |
          if [ -f donations.json ]; then
            TOTAL=$(go run donation/calculate-total.go)
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
          fi
          
      - name: Update README badge
        uses: schneegans/dynamic-badges-action@v1.5.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 86a13cfb221fc094c35b4320e102d759
          filename: total-donations.json
          label: 'Total Donasi'
          message: ${{ format('Rp {0}', steps.total.outputs.total) }}
          color: green
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update donation badge" && git push) 
